### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Benny-** [loov/jsfx#12]
It would be nice if this library was available on a CDN.

Preferable one from this white-list:
https://greasyfork.org/en/help/external-scripts

**Comment by egonelbre** [comment]
I'm not quite sure why it would be beneficial/useful? It's not widely used, so there's no caching win. With bigger projects you probably want to vendor it anyways. With smaller projects you just add a single file to your code.

So, what's the use case for providing it on CDN.

**Comment by Benny-** [comment]
You are right. It does not make a lot of sense for this library.
