### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by qwe19272375** [loov/jsfx#18]
Hi, @loov.
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, and we want to host this project in cdnjs.
Now I just know `jsfx.js` should be added in cdnjs.
I'm curious that `lib/audio.js` and `lib/jsfxlib.js` mentioned in README.md at v1.0 should be added in cdnjs or not? If there is any other files need to be added please tell me, 
[cdnjs/cdnjs#11213](https://github.com/cdnjs/cdnjs/pull/11213)

**Comment by egonelbre** [comment]
Only `jsfx.js` is sufficient. `lib/audio.js` and `lib/jsfxlib.js` don't exist anymore.

And as a general warning, there are no hard guarantees on the sound being generated from version to version. If there is some approach that is 2x faster it will break backwards comp and won't sound the same. That being said, it's very unlikely to happen... or at the very least it would sound similar.

**Comment by egonelbre** [comment]
Ah, you meant for version 1.0? I wouldn't recommen hosting 1.0, more annoying to use and less compatible. I would mark it as 0.9, but not sure what would break with that change, so I've opted not to do it.

But, if you really want then yes, lib/jsfxlib.js, lib/audio.js, lib/jsfx.js are all necessary... depending on the context.

**Comment by yahsieh** [comment]
Thanks, so you recommend we host versions after 1.0?
BTW, I found 1.1.0 and 1.2.0 at npm. If we only need those maybe we can get the files from npm instead.

**Comment by egonelbre** [comment]
Yes, I don't think 1.0 is worth the effort. It's more uncomfortable to use... and most likely people who use it have already vendored (meaning they won't use a CDN).

**Comment by yahsieh** [comment]
Thanks a lot! 😄

**Comment by yahsieh** [comment]
@loov Sorry to bother you again.
I have mistaken that the versions on npm are after `1.0.0`.
Should we host the `jsfx.js` files on GitHub or npm?
Thanks a lot.

cdnjs/cdnjs#11213

**Comment by egonelbre** [comment]
Use npm.

**Comment by yahsieh** [comment]
So we should use the `jsfx.js` at `1.0.0` in npm which is different from `1.0.0` in Github?

**Comment by egonelbre** [comment]
Don't use 1.0 at all.

**Comment by yahsieh** [comment]
Thanks again.
